name: release


on:
  push:
    branches:
      - master
    paths:
      - frontend/**


jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: ./frontend/yarn.lock
    - uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: eu-south-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/WebsiteReleaseManager
        role-session-name: github-oidc
    - run: yarn install --frozen-lockfile --prod
    - run: yarn build
    - run: yarn deploy
    - run: yarn invalidate-cache
      env:
        CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
